INSERT INTO BLC_COUNTRY (ABBREVIATION,NAME) VALUES ('IN', 'INDIA') ;
INSERT INTO BLC_COUNTRY_SUB (ABBREVIATION,ALT_ABBREVIATION,NAME,COUNTRY_SUB_CAT,COUNTRY) VALUES ('IN-AP','AP', 'ANDHRA PRADESH',66, 'IN');

INSERT INTO BLC_COUNTRY_SUB (ABBREVIATION,ALT_ABBREVIATION,NAME,COUNTRY_SUB_CAT,COUNTRY) VALUES ('IN-AP-AKP','AKP', 'ANAKAPALLI',20, 'IN');
INSERT INTO JT_COUNTRY_SUB (ABBREVIATION, REGION) VALUES ('IN-AP-AKP','IN-AP');

INSERT INTO BLC_COUNTRY_SUB (ABBREVIATION,ALT_ABBREVIATION,NAME,COUNTRY_SUB_CAT,COUNTRY) VALUES ('IN-AP-VSKP','VSKP', 'VISAKHAPATNAM',31, 'IN');
INSERT INTO JT_COUNTRY_SUB (ABBREVIATION, REGION) VALUES ('IN-AP-VSKP','IN-AP');

INSERT INTO BLC_COUNTRY_SUB_CAT (COUNTRY_SUB_CAT_ID, NAME) VALUES (87,'Location');

INSERT INTO JT_SUBCATEGORY (ID, CODE, ICON, NAME) VALUES (1,'PILGRIMAGE','','Pilgrimage');
INSERT INTO JT_SUBCATEGORY (ID, CODE, ICON, NAME) VALUES (2,'RESTAURANTS','','Restaurants');
INSERT INTO JT_SUBCATEGORY (ID, CODE, ICON, NAME) VALUES (3,'HOTELS','','Hotels');
INSERT INTO JT_SUBCATEGORY (ID, CODE, ICON, NAME) VALUES (4,'SPORTS','','Sports');
INSERT INTO JT_SUBCATEGORY (ID, CODE, ICON, NAME) VALUES (5,'APARTMENTS_COMMUNITIES','','Apartments or Gated communities');
INSERT INTO JT_SUBCATEGORY (ID, CODE, ICON, NAME) VALUES (6,'RIVER','','River');
INSERT INTO JT_SUBCATEGORY (ID, CODE, ICON, NAME) VALUES (7,'GANESH','','Ganesh');


INSERT INTO BLC_ZIP_CODE (ZIP_CODE_ID, ZIP_CITY, ZIP_LATITUDE, ZIP_LONGITUDE, ZIP_STATE, ZIPCODE) VALUES ('531002', 'IN-AP-AKP', '','','IN-AP', 531002);
INSERT INTO BLC_ZIP_CODE (ZIP_CODE_ID, ZIP_CITY, ZIP_LATITUDE, ZIP_LONGITUDE, ZIP_STATE, ZIPCODE) VALUES ('531001', 'IN-AP-AKP', '','','IN-AP', 531001);

INSERT INTO JT_LOCATION (ID, DESCRIPTION, LATITUDE, LONGITUDE, NAME, CITY, JT_SUBCATEGORY, COUNTRY_SUB_CAT,ZIPCODE)
	VALUES (1, 'Sri Nookambika temple', '','','SRI NOOKAMBIKA TEMPLE', 'IN-AP-AKP', 1,87, '531002');
	
INSERT INTO JT_LOCATION (ID, DESCRIPTION, LATITUDE, LONGITUDE, NAME, CITY, JT_SUBCATEGORY, COUNTRY_SUB_CAT,ZIPCODE)
	VALUES (2, 'Bojjana konda', '','','BOJJANA KONDA', 'IN-AP-AKP', 1,87, '531001');
	
INSERT INTO JT_LOCATION (ID, DESCRIPTION, LATITUDE, LONGITUDE, NAME, CITY, JT_SUBCATEGORY, COUNTRY_SUB_CAT,ZIPCODE)
	VALUES (3, 'Sarada river', '','','SARADA RIVER', 'IN-AP-AKP', 6,87, '531001');	
	
	
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('AR', 'ARUNACHAL PRADESH', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('AS', 'ASSAM', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('BR', 'BIHAR', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('CH', 'CHHATTISGARH', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('GA', 'GOA', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('GJ', 'GUJARAT', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('HR', 'HARYANA', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('HP', 'HIMACHAL PRADESH', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('JH', 'JHARKHAND', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('KA', 'KARNATAKA', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('KL', 'KERALA', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('MP', 'MADHYA PRADESH', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('MH', 'MAHARASHTRA', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('MN', 'MANIPUR', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('MN', 'MEGHALAYA', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('MZ', 'MIZORAM', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('NL', 'NAGALAND', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('OR', 'ODISHA', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('PB', 'PUNJAB', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('RJ', 'RAJASTHAN', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('SK', 'SIKKIM', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('TN', 'TAMILNADU', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('TS', 'TELANGANA', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('TR', 'TRIPURA', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('UP', 'UTTAR PRADESH', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('UT', 'UTTARAKHAND', 'IN');
INSERT INTO BLC_STATE (ABBREVIATION,NAME,COUNTRY) VALUES ('WB', 'WEST BENGAL','IN');