INSERT INTO BLC_ROLE (ROLE_ID, ROLE_NAME) VALUES ('100','ROLE_ITEM_ADMIN');
INSERT INTO BLC_ROLE (ROLE_ID, ROLE_NAME) VALUES ('101','ROLE_ITEM_CMS');
INSERT INTO BLC_ROLE (ROLE_ID, ROLE_NAME) VALUES ('102','ROLE_ITEM_TMS');
INSERT INTO BLC_ROLE (ROLE_ID, ROLE_NAME) VALUES ('103','ROLE_ITEM_DMS');
INSERT INTO BLC_ROLE (ROLE_ID, ROLE_NAME) VALUES ('104','ROLE_AGENT_TMS');
INSERT INTO BLC_ROLE (ROLE_ID, ROLE_NAME) VALUES ('105','ROLE_USER');
INSERT INTO BLC_ROLE (ROLE_ID, ROLE_NAME) VALUES ('105','ROLE_ITEM_PANDIT');